-- TODO:
-- "设置tab键为触发键
-- let g:UltiSnipsExpandTrigger = '<tab>'
-- "设置向后跳转键
-- let g:UltiSnipsJumpForwardTrigger = '<C-j>'
-- "设置向前跳转键
-- let g:UltiSnipsJumpBackwardTrigger = '<C-J>'
-- "设置文件目录
-- let g:UltiSnipsSnippetDirectories=["path/of/snippetDirectories"]
-- "设置打开配置文件时为垂直打开
-- let g:UltiSnipsEditSplit="vertical"
