--vim.cmd([[
--let g:vimwiki_list = [{'path': '~/note',
                      --\ 'syntax': 'markdown', 'ext': '.md'}]
--]])
--vim.cmd([[
--let g:vimwiki_list = [{'path': '~/repos/obsidian/',
                      --\ 'syntax': 'markdown', 'ext': '.md'}]
--]])
